spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogmanager?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    #开启MVC thymeleaf 视图解析
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /**

mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.cai.entity
  config-location: classpath:/mybatisConfig.xml

